title: Zhentao Nie's Homepage
page-top-title: Zhentao Nie
top-section-bg-text: 宇宙中有什么不是暂时的？
home-subtitle: Zhentao Nie&ensp;|&ensp;聂镇涛
copyright-text: '&copy; Zhentao Nie 2026-2027. All Rights Reserved.'
